name: Go

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["main", "feature_branch"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: npm install || npm run deploy

